---

- hosts: all
  tasks:
  
  - name: Display all variables/facts known for a host
    debug:
      var: hostvars
      verbosity: 4

  #
  # Setup hostname
  #

  - name: Set hostname
    shell: echo {{hostname}} >/etc/hostname
    sudo: yes
    sudo_user: root

  - name: Update /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.1\.1'
      line: '127.0.1.1 {{hostname}}'
      owner: root
      group: root
      mode: 0644
    sudo: yes
    sudo_user: root

  #
  # Install basic APT packages
  #

  - name: Update APT index
    apt: update_cache=yes
    sudo: yes
    sudo_user: root

  - name: Install basic APT packages
    apt: pkg={{item}} state=latest
    with_items: 
    - 'vim' 
    - 'bash-completion'
    - 'sudo' 
    - 'curl' 
    - 'htop' 
    - 'tree' 
    - 'jq' 
    - 'screen' 
    - 'bzip2' 
    - 'p7zip-full'
    - 'apt-transport-https'
    - 'ca-certificates'
    - 'gnupg2'
    - 'software-properties-common'
    sudo: yes
    sudo_user: root

  #
  # Install docker-ce and utilities
  #

  - name: Add APT key for Docker repositories
    apt_key:
      url: https://download.docker.com/linux/debian/gpg 
      state: present
    sudo: yes
    sudo_user: root

  - name: Add APT repositories for Docker
    apt_repository:
      repo: deb https://download.docker.com/linux/debian jessie stable 
      state: present
    sudo: yes
    sudo_user: root

  - name: Update APT index
    apt: update_cache=yes
    sudo: yes
    sudo_user: root
   
  - name: Install docker
    apt: pkg=docker-ce state=latest
    sudo: yes
    sudo_user: root

  - name: Run a hello-world Docker container
    shell: docker run hello-world 
    sudo: yes
    sudo_user: root
  
  - set_fact:
      docker_compose_version: '1.16.1'
  
  - name: Download docker-compose binary
    get_url:
      url: 'https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-Linux-{{ansible_architecture}}'
      dest: /usr/local/bin/docker-compose 
      mode: 0774
      owner: root
      group: docker
    sudo: yes
    sudo_user: root
 
  #
  # Configure docker daemon
  #

  - file:
      path: /etc/systemd/system/docker.socket.d
      state: directory
    sudo: yes
    sudo_user: root
    
  - name: Configure socket for docker daemon
    copy:
      content: |
         [Socket]
         ListenStream={{listen_address}}:2375
      dest: /etc/systemd/system/docker.socket.d/10-socket.conf
    notify:
    - 'restart-docker'
    sudo: yes
    sudo_user: root

  - name: Update kernel boot parameters to enable cgroups on memory
    lineinfile:
      dest: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX_DEFAULT[ ]*='
      line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet cgroup_enable=memory swapaccount=1"'  
      mode: 0600
      backup: no
    notify:
    - 'update-grub'
    sudo: yes
    sudo_user: root
  
  #
  # Make user capable of interacting with docker 
  #

  - name: Add user to docker group
    user:
      name: '{{ansible_ssh_user}}'
      groups: docker
      append: yes
    sudo: yes
    sudo_user: root

  - name: Make user-local bin directories
    file: 
      path: ~/bin 
      state: directory

  # 
  # Handlers
  #

  handlers:
  
  - name: 'restart-docker'
    systemd:
      name: docker.service
      daemon_reload: yes
      state: restarted
    sudo: yes
    sudo_user: root

  - name: 'update-grub'
    shell: update-grub
    sudo: yes
    sudo_user: root

